Vue.component('app-header', {
  props: [],
  template:'<header><div class="row"><div class="logo col-lg-3 col-md-3 col-sm-3"><a href="index.html" class=""><img src="images/header_logo-cropped-2.png" alt="header image" class=""></a></div><div class=" d-flex justify-content-center col-lg-9 col-md-9 col-sm-9"><nav class="custom-nav navbar navbar-expand-lg navbar-expand-md"><button class=" navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse col-sm-12 float-right" id="navbarNavDropdown"><ul class="navbar-nav"><li class="nav-item active"><a class="nav-link text-dark" href="../website-proposal/index.html">Home<span class="sr-only ">(current)</span></a></li><li class="nav-item active"><a class="nav-link text-dark" href="#">What is FESC?<span class="sr-only">(current)</span></a></li><li class="nav-item active"><a class="nav-link text-dark" href="#">News<span class="sr-only">(current)</span></a></li><li class="nav-item"><a class="nav-link text-dark" href="#">Energy Industry</a></li><li class="nav-item"><a class="nav-link text-dark" href="#">FESC Resources</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More Information</a><div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"><a class="dropdown-item" href="#">FAQ</a><a class="dropdown-item" href="#">Educational Programs</a><a class="dropdown-item" href="#">Community Outreach Programs</a><a class="dropdown-item" href="../website-proposal/data.html">Research and Data</a></div></li></ul></div></nav></div></div><div class="row mb-4"><h1 class="col-lg-8 col-sm-8">Florida Energy Systems Consortium</h1><input type="text" placeholder="Search..." class="col-lg-4 col-sm-4 searchbar"></div></header>'
  
})

Vue.component('app-footer',{
  template:'<footer class="page-footer font-small blue pt-4 mt-4"><div class="container-fluid text-center text-md-left"><div class="row"><div class="col-md-6"><h5 class="text-uppercase">Florida Energy Resources</h5><ul class="list-unstyled"><li><a href="#">Facilities</a></li><li><a href="#">Institutions</a></li><li><a href="#">Universities</a></li><li><a href="#">Careers</a></li></ul></div><div class="col-md-6"><h5 class="text-uppercase">Links</h5><ul class="list-unstyled"><li><a href="../website-proposal/advisory-board.html">Advisory Board</a></li><li><a href="#!">Leadership and Oversight Board</a></li><li><a href="#!">Faculty</a></li><li><a href="#!">Florida Universities</a></li><li><a href="../website-proposal/contact.html">Contact</a></li></ul></div></div></div><div class="d-flex justify-content-center mt-5"></div><div class="footer-copyright py-3 text-center">© 2018 Copyright:<a href="https://thestevendouglas.github.io/website-proposal/"> Florida Energy Systems Consortium </a></div></footer>'
})

